### ISSUE TITLE
built centos7 vagrant vbox image has sync folder mounting error

### ISSUE THREAD

**Issue by adrianmak** [shiguredo/packer-templates#16]
I used your packer centos 7 template to build a vagrant vbox image
when I startup vagrant box, there is mounting error of sync folder

Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`
vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device

**Comment by amityweb** [comment]
@adrianmak id you fix this? I also get this on the centos-6.6 template.

@Rocklviv I believe build-essential is not for centos, instead the following is used (from what I have read) which is already included in scripts/base.sh:
yum -y install gcc make gcc-c++ kernel-devel-`uname -r` perl

Strangely I did not get the issue earlier the first time I run vagrant up, but subsequent vagrant ups I get it. Even after vagrant destroy and up again.

**Comment by amityweb** [comment]
I thought GuestAdditions was installed already, its certainly in the packer scripts and the files are there on the guest, but I ran this:
~~~
vagrant plugin install vagrant-vbguest
~~~
(got it from here https://github.com/mitchellh/vagrant/issues/3341)

then got this message:
~~~
Installed the plugin 'vagrant-vbguest (0.10.0)'!
~~~

Then on vagrant up I then got new messages about guestadditions being installed but not running, and then it all worked OK:
~~~
GuestAdditions seems to be installed (4.3.20) correctly, but not running.
Starting the VirtualBox Guest Additions [FAILED]
(modprobe vboxguest failed)
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Building the VirtualBox Guest Additions kernel modules
Building the main Guest Additions module[  OK  ]
Building the shared folder support module[  OK  ]
Building the OpenGL support module[  OK  ]
Doing non-kernel setup of the Guest Additions[  OK  ]
Starting the VirtualBox Guest Additions [  OK  ]
~~~

**Comment by arfr** [comment]
This Pull-Request (https://github.com/shiguredo/packer-templates/pull/18) should fix it ;)

**Comment by yuitowest** [comment]
@arfr Thank you for sending a pull request.
I was able to confirem the operation in latest VirtualBox 4.3.20.
This seems to be a bug of VirtulBox.
Please try it in latest VirtualBox.

**Comment by maxkaplan** [comment]
I have tried this in 4.3.24 and it is still not working with chef/centos-7.0 after a sudo yum upgrade -y is ran. What can be done to fix? Thank you

**Comment by yuitowest** [comment]
@maxkaplan I tried `sudo yum upgrade -y`, but succeeded.
Would you tell me detail when it didn't work well?
This is my application versions.
```
$ packer version
Packer v0.7.5

$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

$ VBoxManage --version
4.3.24r98716
```

**Comment by voluntas** [comment]
@maxkaplan ping?

**Comment by maxkaplan** [comment]
@voluntas @yuitowest - The issue was due to virtualbox guest additions. I needed to re-install them after yum upgrade updated the kernel. Hope this helps.

**Comment by yuitowest** [comment]
Thanks!
